DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS retries;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT NOT NULL,
  phone TEXT UNIQUE NOT NULL
);

CREATE TABLE retries (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  phone TEXT UNIQUE NOT NULL,
  retry INTEGER NOT NULL
);


